# The username setup on phpMyAdmin was the root, without any password. Development was done using mysql2.
default: &default
  adapter: mysql2
  username: root
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  # Change all the database to haseebmarketplace, which was created in phpMyAdmin and is the database that will hold all the data.
development:
  <<: *default
  database: haseebmarketplace

test:
  <<: *default
  database: haseebmarketplace

production:
  <<: *default
  database: haseebmarketplace
